fix formatting, formal language, inconsistency fixed
Atlas-OS/Atlas pull request #346
Opened 2022-12-03 13:13 UTC by xyzze

- formatting issue got fixed
- rename Wifi to Wi-Fi
- formal language instead of informal
- minor changes

2022-12-03 13:15 UTC, AnhNguyenlost13 requested changes
I don't think you need to mention Atlas in version selector

2022-12-03 13:16 UTC, xyzze commented
> I don't think you need to mention Atlas in version selector

correct, gotta change that

2022-12-03 13:22 UTC, AnhNguyenlost13 approved these changes

2022-12-04 12:39 UTC, SyrmGIT approved these changes

2022-12-04 12:39 UTC, merged