Updated the Turkish Translation with the main README.md
Atlas-OS/Atlas pull request #793
Opened 2023-05-12 23:07 UTC by Anceph

2023-05-13 13:11 UTC, Xyueta submitted a review, later dismissed

2023-05-13 15:27 UTC, JayXTQ submitted a review, later dismissed

2023-05-14 17:22 UTC, he3als requested changes

2023-05-14 17:22 UTC, he3als commented on translations/README_tr_TR.md
> +      <img alt="License" src="https://img.shields.io/github/license/atlas-os/atlas?style=for-the-badge&logo=github&color=1A91FF"/>
Maybe translate the alt text?

2023-05-15 10:35 UTC, JayXTQ submitted a review, later dismissed

2023-05-15 10:43 UTC, JayXTQ approved these changes
I just fucking reviewed this too cmon now

2023-05-15 10:45 UTC, Xyueta approved these changes

2023-05-15 10:46 UTC, merged